name: clean_kit_flutter
description: 'Starter for your Flutter project with CLEAN Architecture'
publish_to: 'none' # This project is not intended for pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # ğŸ§± Core Flutter & State Management
  cupertino_icons: ^1.0.8 # iOS-style icons
  flutter_bloc: ^9.1.1 # BLoC state management pattern
  get_it: ^9.0.5 # Dependency injection container
  go_router: ^17.0.0 # Declarative routing with navigation guards

  # ğŸŒ Networking & API Communication
  dio: ^5.9.0 # Advanced HTTP client
  connectivity_plus: ^7.0.0 # Internet connectivity monitoring
  http_parser: ^4.1.2 # HTTP headers parsing utilities

  # ğŸ›  Utilities & Functional Programming
  dartz: ^0.10.1 # Functional types like Either, Option
  ansicolor: ^2.0.3 # Colorized console logging
  intl: ^0.20.2 # Internationalization & formatting

  # ğŸ” Secure Local Storage
  flutter_secure_storage: ^9.2.4 # Encrypted key-value storage for sensitive data

  # ğŸ¨ UI Components & Visual Effects
  flutter_svg: ^2.2.2 # Render SVG images
  shimmer: ^3.0.0 # Shimmer loading effect
  cached_network_image: ^3.4.1 # Image caching for network images

  # ğŸ“ File & Media Handling
  file_picker: ^10.3.6 # Pick files from device storage
  image_picker: ^1.2.1 # Pick images from camera/gallery

  # ğŸ”— External Interaction
  url_launcher: ^6.3.2 # Launch URLs, phone dialer, email, etc.
  google_fonts: ^6.3.2 # Use Google Fonts in your app

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0 # Recommended lint rules

flutter:
  uses-material-design: true

  # ğŸ–¼ Assets
  assets:
    - assets/icon/ # App icons
    - assets/image/ # Images used in the app
